feedStore/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

from store.views import ProfileLoginView, CreateUserView

app_name = 'feed-store'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/login/', ProfileLoginView.as_view(), name='login'),
    path(
        'auth/registration/',
        CreateUserView.as_view(
            template_name='registration/registration_form.html',
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('store/', include('store.urls', namespace='store')),
] + static(settings.STATIC_URL,
           document_root=settings.STATIC_ROOT) + static(
               settings.MEDIA_URL,
               document_root=settings.MEDIA_ROOT
            )

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'

urlpatterns = [
    path('', views.about, name='about'),
]

store/urls.py
from django.urls import path

from store import views


app_name = 'store'

urlpatterns = [
    # url связанные с продукцией
    path('', views.product_list, name='product-list'),
    path('<int:pk>/', views.product_detail, name='product-detail'),

    # url связанные с заказами корзины
    path('order/', views.order_list, name='order-list'),
    path('add_order/', views.order_create, name='order-add'),

    # url связанные с одиночными заказами
    path(
        '<int:pk>/single_add_order/',
        views.order_add,
        name='single-order-create'
    ),
    path(
        'order/<int:pk>/status-ready/',
        views.order_ready,
        name='order_ready'
    ),
    path(
        'order/<int:pk>/status-cancelled/',
        views.order_cancelled,
        name='order_cancelled'
    ),
    path(
        'order/<int:pk>/status-confirmed/',
        views.order_confirmed,
        name='order_confirmed'
    ),

    # url связанные с корзиной
    path('<int:product_id>/cart_add/', views.cart_add, name='cart_add'),
    path(
        '<int:product_id>/cart_revove/',
        views.cart_remove,
        name='cart_remove'
    ),
    path('cart/', views.cart_detail, name='cart_detail'),

    # url связанные с пользователями
    path('profile/<name>/', views.info_profile, name='profile'),
    path(
        'profile/<name>/edit_info/',
        views.info_user_edit,
        name='info-user-edit'
    ),

    # url связвнные с администрированием
    path('delivery/', views.delivery_page, name='delivery'),
]

templates/includes/cart_card.html
{% load static %}
<div class="col d-flex align-items-stretch md-4">
  <div class="card mb-4 box-shadow d-flex">
    <div class="card-body">
      <a href="{{ product.get_absolute_url }}">
        <img class="card-img-top" src="
          {% if product.image %}
            {{ product.image.url }}
          {% else %}
            {% static "img/Unknown.jpeg" %}
          {% endif %}">
      </a>
      <div>
        <h5 class="card-title">{{ product.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>Кол-во: {{ item.quantity }}</small>
        </h6>
      </div>
      <a href="{% url 'store:cart_remove' product.id%}" class="btn btn-primary">Удалить товар</a>
    </div>
  </div>
</div>

templates/includes/footer.html
<footer class="footer fixed-bottom border-top text-center py-2 mt-10" style="background-color: white;">
  <p>© FeedStore</p>    
</footer>

templates/includes/header.html
{% load static %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'pages:about' %}">
        <img src="{% static 'img/два хвоста.png' %}" width="120" height="30" class="d-inline-block align-top" alt="">
      </a>
      {% with request.resolver_match.view_name as view_name %}
        <ul class="nav  nav-pills">
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'pages:about' %} text-white {% endif %}" href="{% url 'pages:about' %}">
              О нас
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if view_name == 'store:product-list' %} text-white {% endif %}" href="{% url 'store:product-list' %}">
              Товары
            </a>
          </li>
          {% if request.user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'store:delivery' %} text-white {% endif %}" href="{% url 'store:delivery' %}">
                Доставка
              </a>
            </li>
          {% endif %}
          <li class="nav-item">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link {% if view_name == 'store:cart_detail' %} text-white {% endif %}" href="{% url 'store:cart_detail' %}">
                <img src="{% static 'img/cart.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
              </a>
            </li>
            <div class="btn-group" role="group" aria-label="Basic outlined example">
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'store:profile' user.username %}">{{ user.username }}</a></button>
              <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                  href="{% url 'logout' %}">Выйти</a></button>
            </div>
            {% else %}
              <div class="btn-group" role="group" aria-label="Basic outlined example">
                <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                    href="{% url 'login' %}">Войти</a></button>
                <button type="button" class="btn btn-outline-primary"><a class="text-decoration-none text-reset"
                    href="{% url 'registration' %}">Регистрация</a></button>
              </div>
            {% endif %}
          </li>
        </ul>
      {% endwith %}
    </div>
  </nav>
</header>

templates/includes/order_card.html
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 40rem;">
      <div class="card-body">
        <h5 class="card-title"> Заказ №{{ order.id }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {{ order.created_at|date:"d E Y, H:i" }}
          </small>
        </h6>
        <p class="card-text">
          Имя: {{ order.first_name }}<br>
          Фамилия: {{ order.last_name }}<br>
          Адрес: <a href="#">{{ order.city }}, {{ order.street }}, д. {{ order.building }}, подъезд {{ order.entrance }}</a><br>
          Номер телефона: <a href="tel:{{ order.number_phone }}">{{ order.number_phone }}</a><br>
          Статус: {{ order.status }}<br>
        </p>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Товар</th>
                <th scope="col">Кол-во</th>
              </tr>
            </thead>
            <tbody>
              {% for item in order_items %}
                {% if item.order == order %}
                  <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ item.product.title }}</td>
                    <td>{{ item.quantity }}</td>
                  </tr>
                {% endif %}
              {% endfor %}
            </tbody>
          </table>
          {% if order.status != 'Доставлен' and order.status != 'Отменен' %}
            {% if order.status != 'Отменен' %}
            <a href="{% url 'store:order_cancelled' order.id %}" class="btn btn-primary">Отменить</a>
            {% endif %}
            {% if request.user.is_superuser %}
              {% if order.status != 'Подтвержден' and view_name == 'store:delivery' %}
              <a href="{% url 'store:order_confirmed' order.id %}" class="btn btn-primary">Подтвердить</a>
              {% endif %}
              <a href="{% url 'store:order_ready' order.id %}" class="btn btn-primary">Доставлен</a>
            {% endif %}
          {% endif %}
      </div>
    </div>
  </div>

templates/includes/paginator.html
{% if products.has_other_pages %}
  <nav aria-label="Page navigation" class="my-5">
    <ul class="pagination justify-content-center">
      {% if products.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
          <a class="page-link" href="?page={{ products.previous_page_number }}">
            << </a>
        </li>
      {% endif %}
      {% for i in products.paginator.page_range %}
        {% if products.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
      {% endfor %}
      {% if products.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ products.next_page_number }}">
            >>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="?page={{ products.paginator.num_pages }}">
            Последняя
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/includes/product_card.html
{% load static %}
<div class="col d-flex align-items-stretch md-4">
    <div class="card mb-4 box-shadow d-flex">
      <div class="card-body">
        {% if product.image %}
          <a href="{{ product.image.url }}" target="_blank">
            <img class="card-img-top" src="{{ product.image.url }}">
          </a>
        {% else %}
          <a href="" target="_blank">
            <img class="card-img-top" src="{% static 'img/Unknown.jpeg' %}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ product.title|truncatechars_html:50 }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not product.is_published %}
              <p class="text-danger">Пост снят с публикации админом</p>
            {% elif not product.category.is_published %}
              <p class="text-danger">Выбранная категория снята с публикации админом</p>
            {% endif %}
            {{ product.created_at|date:"d E Y, H:i" }} <br>
            Осталось: {{ product.value }} <br>
          </small>
        </h6>
        <p class="card-text">{{ product.text|truncatechars_html:100 }}</p>
        <a href="{% url 'store:product-detail' product.id %}" class="button light">Подробнее...</a>
        <p class="card-text"><b>Цена:</b> {{ product.price }} руб.</p>
        <a href="{% url 'store:single-order-create' product.id %}" class="btn btn-primary">Заказать</a>
        {% load django_bootstrap5 %}
        <form method="post" action="{% url 'store:cart_add' product.id %}">
          {% csrf_token %}
          {% bootstrap_form form %}
          {% bootstrap_button button_type="submit" content="Добавить в корзину" %}
        </form>
      </div>
    </div>
</div>