feedStore/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.conf import settings
from django.conf.urls.static import static

from store.views import ProfileLoginView, CreateUserView

app_name = 'feed-store'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/login/', ProfileLoginView.as_view(), name='login'),
    path(
        'auth/registration/',
        CreateUserView.as_view(
            template_name='registration/registration_form.html',
            success_url=reverse_lazy('login'),
        ),
        name='registration',
    ),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('pages.urls', namespace='pages')),
    path('store/', include('store.urls', namespace='store')),
] + static(settings.STATIC_URL,
           document_root=settings.STATIC_ROOT) + static(
               settings.MEDIA_URL,
               document_root=settings.MEDIA_ROOT
            )

pages/urls.py
from django.urls import path
from pages import views

app_name = 'pages'

urlpatterns = [
    path('', views.about, name='about'),
]

store/urls.py
from django.urls import path

from store import views


app_name = 'store'

urlpatterns = [
    # url связанные с продукцией
    path('', views.product_list, name='product-list'),
    path('<int:pk>/', views.product_detail, name='product-detail'),

    # url связанные с заказами корзины
    path('order/', views.order_list, name='order-list'),
    path('add_order/', views.order_create, name='order-add'),

    # url связанные с одиночными заказами
    path(
        '<int:pk>/single_add_order/',
        views.order_add,
        name='single-order-create'
    ),
    path(
        'order/<int:pk>/status-ready/',
        views.order_ready,
        name='order_ready'
    ),
    path(
        'order/<int:pk>/status-cancelled/',
        views.order_cancelled,
        name='order_cancelled'
    ),
    path(
        'order/<int:pk>/status-confirmed/',
        views.order_confirmed,
        name='order_confirmed'
    ),

    # url связанные с корзиной
    path('<int:product_id>/cart_add/', views.cart_add, name='cart_add'),
    path(
        '<int:product_id>/cart_revove/',
        views.cart_remove,
        name='cart_remove'
    ),
    path('cart/', views.cart_detail, name='cart_detail'),

    # url связанные с пользователями
    path('profile/<name>/', views.info_profile, name='profile'),
    path(
        'profile/<name>/edit_info/',
        views.info_user_edit,
        name='info-user-edit'
    ),

    # url связвнные с администрированием
    path('delivery/', views.delivery_page, name='delivery'),
]

store/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from store.models import Order


User = get_user_model()


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'email')


class InfoUserForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'number_phone',
            'city',
            'street',
            'building',
            'entrance',
            'location',
        )


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = ('user', 'status', 'is_published')


class ProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email'
        )


class CartAddProductForm(forms.Form):
    update = forms.BooleanField(
        required=False,
        initial=False,
        widget=forms.HiddenInput
    )

store/views.py
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from store.models import Product, Order, OrderItem, Location
from store.forms import (
    OrderForm,
    CartAddProductForm,
    InfoUserForm,
    UserRegistrationForm
)
from store.cart import Cart
from store.utils import get_info_order
from feedStore.settings import PAGINATE_STEP


User = get_user_model()


class ProfileLoginView(LoginView):
    def get_success_url(self):
        url = reverse(
            'store:profile',
            args=(self.request.user.get_username(),)
        )
        return url


class CreateUserView(CreateView):
    form_class = UserRegistrationForm

    class Meta:
        model = User
        fields = ('username', 'password')


@login_required
def info_profile(request, name):
    template_name = 'store/profile.html'
    user = get_object_or_404(
        User,
        username=name,
    )
    orders = user.order.all().order_by('-created_at')
    order_items = OrderItem.objects.all()
    context = {
        'orders': orders,
        'order_items': order_items
    }
    return render(request, template_name, context)


@login_required
def info_user_edit(request, name):
    template_name = 'store/info-user.html'
    instance = request.user
    form = InfoUserForm(request.POST or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            info = form.save(commit=False)
            info.save()
            return redirect('store:profile', name)
    context = {
        'form': form,
        'info': instance,
    }
    return render(request, template_name, context)


def product_list(request):
    template_name = 'store/store_pages.html'
    products_list = Product.objects.filter(is_published=True)
    paginator = Paginator(products_list, PAGINATE_STEP)
    page_number = request.GET.get('page')
    products = paginator.get_page(page_number)
    form = CartAddProductForm
    context = {
        'products': products,
        'form': form,
    }
    return render(request, template_name, context)


def product_detail(request, pk):
    template_name = 'store/detail.html'
    form = OrderForm
    product = get_object_or_404(Product, id=pk)
    context = {
        'product': product,
        'form': form
    }
    return render(request, template_name, context)


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=1,
                 update_quantity=cd['update'])
    return redirect('store:product-list')


@login_required
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('store:cart_detail')


@login_required(login_url='login')
def cart_detail(request):
    cart = Cart(request)
    return render(request, 'store/cart_detail.html', {'cart': cart})


@login_required(login_url='login')
def order_list(request):
    template_name = 'store/admin_pages.html'
    orders = Order.objects.filter(is_published=True)
    context = {
        'orders': orders
    }
    return render(request, template_name, context)


@login_required(login_url='login')
def order_add(request, pk):
    product = get_object_or_404(Product, id=pk)
    form = OrderForm(request.POST or None)
    if request.user.is_info:
        order = get_info_order(request.user)
        form = OrderForm(request.POST or None, instance=order)
        order.delete()
    if request.method == 'POST':
        if form.is_valid():
            order = form.save(commit=False)
            order.product = product
            order.user = request.user
            order.save()
            OrderItem.objects.create(
                order=order,
                product=product,
                quantity=1,
                price=product.price
            )
            product.value = product.value - 1
            product.save()
            return redirect('store:profile', request.user.username)
    template_name = 'store/single_order_create.html'
    context = {
        'form': form,
        'product': product
    }
    return render(request, template_name, context)


@login_required(login_url='login')
def order_create(request):
    template_name = 'store/order_create.html'
    cart = Cart(request)
    form = OrderForm(request.POST or None)
    if request.user.is_info:
        order = get_info_order(request.user)
        form = OrderForm(request.POST or None, instance=order)
        order.delete()
    if request.method == 'POST':
        if len(cart) == 0:
            form.add_error(
                error='Добавте товар(ы) в корзину.',
                field='__all__'
            )
            return render(
                request,
                template_name,
                {
                    'cart': cart,
                    'form': form,
                }
            )
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            for item in cart:
                OrderItem.objects.create(
                    order=order,
                    product=item['product'],
                    price=item['price'],
                    quantity=item['quantity']
                )
                item['product'].value = item['product'].value - item['quantity']
                item['product'].save()
            cart.clear()
            return redirect('store:profile', request.user.username)
    context = {
        'cart': cart,
        'form': form,
    }
    return render(request, template_name, context)


def order_ready(request, pk):
    order = get_object_or_404(Order, id=pk)
    order.status = 'Доставлен'
    order.save()
    return redirect('store:profile', request.user.username)


def order_confirmed(request, pk):
    order = get_object_or_404(Order, id=pk)
    order.status = 'Подтвержден'
    order.save()
    return redirect('store:profile', request.user.username)


def order_cancelled(request, pk):
    order = get_object_or_404(Order, id=pk)
    order.status = 'Отменен'
    order.save()
    return redirect('store:profile', request.user.username)


@login_required(login_url='login')
def delivery_page(request):
    order_items = OrderItem.objects.all()
    template_name = 'store/delivery_page.html'
    if not request.user.is_superuser:
        return render(request, 'error/403.html')
    menu_dict = list()
    for location in Location.objects.all():
        menu_dict.append(
            {
                f'{location.name}': location.order.all()
            }
        )
    context = {
        'menu_dict': menu_dict,
        'order_items': order_items
    }
    return render(request, template_name, context)

templates/store/admin_pages.html
{% extends "base.html" %}
{% block title %}
  Список заказов
{% endblock %}
{% block content %}
  {% for order in orders %}
    <article class="mb-5">
      {% include "includes/order_card.html" %}
    </article>
  {% endfor %}
{% endblock %}

templates/store/cart_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Корзина покупок
{% endblock %}
{% block content %}
<div class="col d-flex justify-content-center">
    <div class="card" style="width: 80rem;">
      <div class="card-body">
        <div class="row row-cols-1 row-cols-md-4 g-4">
            {% for item in cart %}
                {% with product=item.product %}
                    {% include "includes/cart_card.html" %}
                {% endwith %}
            {% endfor %}
        </div>
        <br><br>
        <tr class="total">
            <td>Итог:</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
        <p class="justify-content-center">
            <a href="{% url 'store:product-list' %}" class="btn btn-primary">Продолжить покупки</a>
            <a href="{% url 'store:order-add' %}" class="btn btn-primary">Заказать</a>
        </p>
        </div>
    </div>
</div>
{% endblock %}

templates/store/delivery_page.html
{% extends "base.html" %}
{% block title %}
  Страница доставщика
{% endblock %}
{% block content %}
    {% for dict in menu_dict %}
        {% for key,value in dict.items %}
        <article class="mb-5">
            <div class="col d-flex justify-content-center">
                <div class="card" style="width: 60rem; background-color: #d8bfd8">
                  <div class="card-body">
                    <h5 class="card-title text-center">{{key}}</h5>
                    <br>
                    {% for order in value %}
                        <article class="mb-5">
                          {% if order.status != 'Доставлен' %}
                            {% include 'includes/order_card.html' %}
                          {% endif %}
                        </article>
                    {% endfor %}
                  </div>
                </div>
            </div>
        </article>
        {% endfor %}
    {% endfor %}
{% endblock %}

templates/store/detail.html
{% extends "base.html" %}
{% block title %}
  {{ product.title }}
{% endblock %}
{% block content %}
  <div class="col d-flex justify-content-center">
    <div class="card" style="width: 60rem;">
      <div class="card-body">
        {% if product.image %}
          <a href="{{ product.image.url }}" target="_blank">
            <img class="border-3 rounded img-fluid img-thumbnail mb-2 mx-auto d-block" src="{{ product.image.url }}">
          </a>
        {% endif %}
        <h5 class="card-title">{{ product.title }}</h5>
        <h5 class="card-title">Осталось: {{ product.value }} kg</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <small>
            {% if not product.is_published %}
              <p class="text-danger">Товар снят с продажи</p>
            {% elif not product.category.is_published %}
              <p class="text-danger">Товары этой категории сняты с продажи</p>
            {% endif %}
          </small>
        </h6>
        <p class="card-text"><b>Описание: </b>{{ product.text|linebreaksbr }}<br><b>Производитель: </b>{{ product.brand }}</p>
      </div>
    </div>
  </div>

{% endblock %}

templates/store/info-user.html
{% extends "base.html" %}

{% block title %}Редактирование анкеты{% endblock %}

{% block content %}
<div class="col d-flex justify-content-center">
    <div class="card mb-4 box-shadow d-flex" style="width: 40rem;">
        <div class="card-body">
            <h1>Редактирование анкеты данных пользователя</h1>
            {% if instance is not None %}
                <p>Данная анкета необязательна к заполнению. 
                    Но если вы частый посетитель нашего сайта, 
                    то данные из этой анкеты ускорят оформление заказов в будущем.
                </p>
            {% endif %}
            {% load django_bootstrap5 %}
            <form action="{% url 'store:info-user-edit' request.user.username %}" method="post" class="order-form">
                {% csrf_token %}
                {% bootstrap_form form %}
                <p><input class="btn btn-primary" type="submit" value="Отправить данные"></p>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/store/order_create.html
{% extends "base.html" %}

{% block title %}Создание заказа{% endblock %}

{% block content %}
<div class="col d-flex justify-content-center">
    <div class="card mb-4 box-shadow d-flex" style="width: 40rem;">
        <div class="card-body">
            <h1>Создание заказа</h1>
            <div class="order-info">
                <h3>Ваш заказ</h3>
                <ul>
                    {% for item in cart %}
                        <li>
                            {{ item.quantity }} x {{ item.product.name }}
                            <span>{{ item.total_price }} руб.</span>
                        </li>
                    {% endfor %}
                </ul>
                <p>Цена за заказ: {{ cart.get_total_price }} руб.</p>
            </div>

            {% load django_bootstrap5 %}
            <form action="." method="post" class="order-form">
                {% csrf_token %}
                {% bootstrap_form form %}
                <!--{{ form.as_p }}-->
                <p><input class="btn btn-primary" type="submit" value="Офорить заказ"></p>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/store/profile.html
{% extends "base.html" %}
{% block content %}
<div class="py-2" style="background-color: white;">
      <h1 class="mb-5 text-center ">Страница пользователя {{ profile.username }}</h1>
      <small>
        <ul class="list-group list-group-horizontal justify-content-center mb-3">
          <li class="list-group-item text-muted">Имя пользователя: {% if profile.get_full_name %}{{ profile.get_full_name }}{% else %}не указано{% endif %}</li>
          <li class="list-group-item text-muted">Регистрация: {{ profile.date_joined }}</li>
          <li class="list-group-item text-muted">Роль: {% if profile.is_staff %}Админ{% else %}Пользователь{% endif %}</li>
        </ul>
        <ul class="list-group list-group-horizontal justify-content-center" style="background-color:white">
          <a href="{% url 'store:info-user-edit' request.user.username %}" class="btn btn-sm text-muted">Редактировать анкету</a>
          <a class="btn btn-sm text-muted" href="{% url 'password_change' %}">Изменить пароль</a>
        </ul>
      </small>
</div>
  <br>
    {% for order in orders %}
        <article class="mb-5">
            {% include "includes/order_card.html" %}
        </article>
    {% endfor %}
{% endblock %}

templates/store/single_order_create.html
{% extends "base.html" %}

{% block title %}Создание заказа{% endblock %}

{% block content %}
<div class="col d-flex justify-content-center">
    <div class="card mb-4 box-shadow d-flex" style="width: 40rem;">
        <div class="card-body">
            <h1>Создание заказа</h1>
            <div class="order-info">
                <h3>Ваш заказ</h3>
                <ul>
                    <li>
                        1 x {{ product.name }}
                        <span>{{ product.price }} руб.</span>
                    </li>
                </ul>
                <p>Цена за заказ: {{ product.price }} руб.</p>
            </div>

            {% load django_bootstrap5 %}
            <form action="{% url 'store:single-order-create' product.id %}" method="post" class="order-form">
                {% csrf_token %}
                {% bootstrap_form form %}
                <p><input class="btn btn-primary" type="submit" value="Офорить заказ"></p>
                {% csrf_token %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/store/store_pages.html
{% extends "base.html" %}
{% block title %}
  Товары
{% endblock %}
{% block content %}
<div class="row row-cols-1 row-cols-md-4 g-4">
  {% for product in products %}
    {% include "includes/product_card.html" %}
  {% endfor %}
</div>
{% include "includes/paginator.html" %}
{% endblock %}